
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package gramatica;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SIGNO_MAS = 19;
  public static final int MENOR = 4;
  public static final int PAREN_FIN = 9;
  public static final int PERCENT = 2;
  public static final int DATA_TYPE = 27;
  public static final int IGUAL = 3;
  public static final int FIN_PARA = 24;
  public static final int HASTA = 25;
  public static final int MENOR_IGUAL = 17;
  public static final int MAYOR_IGUAL = 18;
  public static final int PARA = 23;
  public static final int LLAVE_FIN = 11;
  public static final int CORCH_FIN = 7;
  public static final int DOS_PUNTOS = 14;
  public static final int COMA = 12;
  public static final int SIGNO_POR = 21;
  public static final int IGUAL_IGUAL = 15;
  public static final int NO_IGUAL = 16;
  public static final int MAYOR = 5;
  public static final int PAREN_INI = 8;
  public static final int EOF = 0;
  public static final int STRING_VALUE = 28;
  public static final int INTEGER_VALUE = 29;
  public static final int error = 1;
  public static final int SIGNO_DIV = 22;
  public static final int PUNTO_COMA = 13;
  public static final int LLAVE_INI = 10;
  public static final int CORCH_INI = 6;
  public static final int ID_VALUE = 30;
  public static final int HACER = 26;
  public static final int SIGNO_MIN = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PERCENT",
  "IGUAL",
  "MENOR",
  "MAYOR",
  "CORCH_INI",
  "CORCH_FIN",
  "PAREN_INI",
  "PAREN_FIN",
  "LLAVE_INI",
  "LLAVE_FIN",
  "COMA",
  "PUNTO_COMA",
  "DOS_PUNTOS",
  "IGUAL_IGUAL",
  "NO_IGUAL",
  "MENOR_IGUAL",
  "MAYOR_IGUAL",
  "SIGNO_MAS",
  "SIGNO_MIN",
  "SIGNO_POR",
  "SIGNO_DIV",
  "PARA",
  "FIN_PARA",
  "HASTA",
  "HACER",
  "DATA_TYPE",
  "STRING_VALUE",
  "INTEGER_VALUE",
  "ID_VALUE"
  };
}

